config/routes.rb
PopHealth::Application.routes.draw do

  apipie

  devise_for :users, :controllers => {:registrations => "registrations"}

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  post 'api/measures/finalize'
  post 'api/measures/update_metadata'
  get "logs/index"
  post 'home/set_reporting_period'
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default"
  get 'home/check_authorization'
  delete "practices/remove_patients"
  delete "practices/remove_providers"

  post "admin/providers", :to => 'admin/providers#create'
  put 'admin/patient', :to => 'admin/patients#upload_single_patient'

  root :to => 'home#index'

  resources :practices

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams

  namespace :api do
    get 'reports/qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
    get 'reports/cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/patients', :to => 'reports#patients'
    get 'reports/measures_spreadsheet', :to =>'reports#measures_spreadsheet'
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/team_report', :to => 'reports#team_report'
    post 'session/sso', :to => 'sessions#check_auth'

    resources :sessions

    resources :practices
    resources :teams
    namespace :admin do
      resource :caches do
        collection do
          get :count
        end
      end
      resource :patients do
        collection do
          get :count
        end
      end
      resource :providers do
        collection do
          get :count
        end
      end
      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
    resources :providers do
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end
    end
    resources :patients do
      member do
        get :results
      end
    end

    resources :measures

    resources :queries do
       member do
        get :patients
        get :patient_results
        put :recalculate
       end
    end
  end

end

app/models/measure.rb
class Measure

  GROUP = {'$group' => {_id: "$id", 
                        name: {"$first" => "$name"},
                        description: {"$first" => "$description"},
                        sub_ids: {'$push' => "$sub_id"},
                        subs: {'$push' => {"sub_id" => "$sub_id", "short_subtitle" => "$short_subtitle"}},
                        category: {'$first' => "$category"}}}

  CATEGORY = {'$group' => {_id: "$category",
                           measures: {'$push' => {"id" => "$_id", 
                                                  'name' => "$name",
                                                  'description' => "$description",
                                                  'subs' => "$subs",
                                                  'sub_ids' => "$sub_ids"
                                                  }}}}

  ID = {'$project' => {'category' => '$_id', 'measures' => 1, '_id' => 0}}
  
  SORT = {'$sort' => {"category" => 1}}

  def self.all
    MONGO_DB['measures'].find({})
  end

  def self.categories
    aggregate(GROUP, CATEGORY, ID, SORT)
  end
	
  def self.list
    aggregate({'$project' => {'id' => 1, 'sub_id' => 1, 'name' => 1, 'short_subtitle' => 1}})
  end

  private

  def self.aggregate(*pipeline)
    Mongoid.default_session.command(aggregate: 'measures', pipeline: pipeline)['result']
  end

end

app/controllers/api/measures_controller.rb
require 'measures/loader.rb'
require 'hds/measure.rb'
module Api
  class MeasuresController < ApplicationController
    resource_description do
      short 'Measures'
      formats ['json']
      description "This resource allows for the management of clinical quality measures in the popHealth application."
    end
    include PaginationHelper
    before_filter :authenticate_user!
    before_filter :validate_authorization!
    before_filter :set_pagination_params, :only=> :index
    before_filter :create_filter , :only => :index
    before_filter :update_metadata_params, :only => :update_metadata

    api :GET, "/measures", "Get a list of measures"
    param_group :pagination, Api::PatientsController
    def index
      measures = HealthDataStandards::CQM::Measure.where(@filter)
      render json: paginate(api_measures_url, measures), each_serializer: HealthDataStandards::CQM::MeasureSerializer
    end

    api :GET, "/measures/:id", "Get an individual clinical quality measure"
    param :id, String, :desc => 'The HQMF id for the CQM to calculate', :required => true
    param :sub_id, String, :desc => 'The sub id for the CQM to calculate. This is popHealth specific.', :required => false
    def show
      measure = HealthDataStandards::CQM::Measure.where({"hqmf_id" => params[:id], "sub_id"=>params[:sub_id]}).first
      render :json=> measure
    end

    api :POST, "/measures", "Load a measure into popHealth"
    description "The uploaded measure must be in the popHealth JSON measure format. This will not accept HQMF definitions of measures."
    def create
      authorize! :create, HealthDataStandards::CQM::Measure
      measure_details = {
        'type'=>params[:measure_type],
        'episode_of_care'=>params[:calculation_type] == 'episode',
        'category'=> params[:category].empty? ?  "miscellaneous" : params[:category],
        'lower_is_better'=> params[:lower_is_better]
      }
      ret_value = {}
      hqmf_document = Measures::Loader.parse_model(params[:measure_file].tempfile.path)
      if measure_details["episode_of_care"]
        Measures::Loader.save_for_finalization(hqmf_document)
        ret_value= {episode_ids: hqmf_document.specific_occurrence_source_data_criteria().collect{|dc| {id: dc.id, description: dc.description}},
                    hqmf_id: hqmf_document.hqmf_id,
                    vsac_username: params[:vsac_username],
                    vsac_password: params[:vsac_password],
                    category: measure_details["category"],
                    lower_is_better: measure_details[:lower_is_better],
                    hqmf_document: hqmf_document
                  }
      else
        Measures::Loader.generate_measures(hqmf_document,params[:vsac_username],params[:vsac_password],measure_details)
      end
      render json: ret_value
      rescue => e
        render text: e.to_s, status: 500
    end

    api :DELETE, '/measures/:id', "Remove a clinical quality measure from popHealth"
    param :id, String, :desc => 'The HQMF id for the CQM to calculate', :required => true
    description "Removes the measure from popHealth. It also removes any calculations for that measure."
    def destroy
      authorize! :delete, HealthDataStandards::CQM::Measure
      measure = HealthDataStandards::CQM::Measure.where({"hqmf_id" => params[:id]})
      #delete all of the pateint and query cache entries for the measure
      HealthDataStandards::CQM::PatientCache.where({"value.measure_id" => params[:id]}).destroy
      HealthDataStandards::CQM::QueryCache.where({"measure_id" => params[:id]}).destroy
      measure.destroy
      render :status=>204, :text=>""
    end


    def update_metadata
      authorize! :update, HealthDataStandards::CQM::Measure
      measures = HealthDataStandards::CQM::Measure.where({ hqmf_id: params[:hqmf_id]})
      measures.each do |m|
        m.update_attributes(params[:measure])
        m.save
      end
      render json:  measures,  each_serializer: HealthDataStandards::CQM::MeasureSerializer
      rescue => e
        render text: e.to_s, status: 500
    end


    def finalize
      measure_details = {
          'episode_ids'=>params[:episode_ids],
          'category' => params[:category],
          'measure_type' => params[:measure_type],
          'lower_is_better' => params[:lower_is_better]

       }
      Measures::Loader.finalize_measure(params[:hqmf_id],params[:vsac_username],params[:vsac_password],measure_details)
      measure = HealthDataStandards::CQM::Measure.where({hqmf_id: params[:hqmf_id]}).first
      render json: measure, serializer: HealthDataStandards::CQM::MeasureSerializer
      rescue => e
        render text: e.to_s, status: 500
    end

  private

    def validate_authorization!
      authorize! :read, HealthDataStandards::CQM::Measure
    end

    def create_filter
      measure_ids = params[:measure_ids]
      @filter = measure_ids.nil? || measure_ids.empty? ? {} : {:hqmf_id.in => measure_ids}
    end

    def update_metadata_params
      params[:measure][:lower_is_better] = nil if params[:measure][:lower_is_better].blank?
    end

  end
end

app/views/measures/_measure_compare.html.erb
<% subs_iterator(measure_compare['subs']) do |sub| %>
	<tr style="<%=display_row(measure_compare['id'], current_user.selected_measures)%>" data-measure="<%=measure_compare['id']%>" data-measure-sub="<%= sub %>" class="measure">
		<% if sub.nil? || sub == 'a' %>
			<td class="name" style="height: 55px; width:240px;"><%= (can? :manage, :providers) ? link_to(raw("<span title='#{measure_compare['description']}' class='vtip'>#{measure_compare['name']}</span>"), "#{measure_path(measure_compare['id'], sub)}/providers") : "#{measure_compare['id']}: #{measure_compare['name']}" %></td>
		<% else %>
			<td class="name" style="height: 55px; width:240px;"/>
		<% end %>
		
		<% if sub %>
			<td class="subtitle"><%= (can? :manage, :providers) ? link_to("#{measure_compare['short_subtitles'][sub]}", "#{measure_path(measure_compare['id'], sub)}/providers") : "#{measure_compare['short_subtitles'][sub]}" %></td>
		<% else %>
			<td class="subtitle" />
	  <% end %> 
		<td class="compareValue phval numeratorCompare"><span class="numeratorValue"></span></td>
		<td class="compareValue compare numeratorCompare"><span class="numeratorValue"></span></div></td>
		<td class="compareValue phval denominatorCompare"><span class="denominatorValue"></span></div></td>
		<td class="compareValue compare denominatorCompare"><span class="denominatorValue"></span></div></td>
	  <td class="barChart">
	    <div style="padding-bottom:4px;">
  	    <%= render :partial => "shared/table_bar", locals: {numerator: 0, denominator:0, patient_count: 0, exclusions: 0}%> 
	    </div> <span style="color: #CCC; font-size: 10px;">PH</span>
	    <div>
  	    <%= render :partial => "shared/table_bar", locals: {numerator: 0, denominator:0, patient_count: 0, exclusions: 0, compare: true}%> 
	    </div> <span style="color: #CCC; font-size: 10px;">QDC</span>
	  </td>
	</tr>
<% end %>

app/views/measures/compare.html.erb
<% content_for :head do %>
<script type="text/javascript" charset="utf-8">
  <% if @selected_provider %>
    Page.npi = '<%=@selected_provider.npi%>'
    Page.compare_report = 1
  <% end %>
  Page.onLoad = Compare.onLoad;
  
    $(document).ready(function() {

      $("#slider-range").slider({
            range: true,
            min: 0,
            max: 100,
            values: [ Compare.minHighlight, Compare.maxHighlight ],
            slide: function( event, ui ) {
              $("#highlight_values").html( ' delta <= ' + ui.values[ 0 ] + "% Green and delta >= " + ui.values[ 1 ] + '% Red ' );
              $('#green-slide').css('width', ui.values[ 0 ] + '%');
              $('#red-slide').css('width', (100-ui.values[ 1 ]) + '%');
              $('#red-slide').css('left', (ui.values[ 1 ]) + '%');
              Compare.minHighlight = ui.values[ 0 ]
              Compare.maxHighlight = ui.values[ 1 ]
            },
            change: function( event, ui ) {
              Compare.highlightData();
            }
          });
          
    });
  
</script>
<% end -%>

  
  <div id="pageContent">
    <div id="providerReports">
    <div class="groupList">
      <ul>
        <li>
          <label class="open">Core Measures</label>
          <div class="measureItemList expandableList">
            <ul>
              <% @core_measures.each do |measure| -%>
               <li class="<%= measure_selected(measure['id'], current_user.selected_measures) %>" data-measure-id="<%= measure['id'] %>" data-sub-measures="<%=measure['subs'].join(',')%>" data-category="Core"><%= measure['name'] %></li>
             <% end %>
             <% @core_alt_measures.each do |measure| -%>
               <li class="<%= measure_selected(measure['id'], current_user.selected_measures) %>" data-measure-id="<%= measure['id'] %>" data-sub-measures="<%=measure['subs'].join(',')%>" data-category="Core Alternate"><span class="note">**</span><%= measure['name'] %></li>
             <% end %>
            </ul>
            <p class="note"><em>** core alternate measures</em></p>
          </div>
        </li>
      </ul>
    </div>
    <div class="groupList">
      <ul>
        <li>
          <label class="open">Alternate Measures</label>
          <div class="expandableList">
        
            <% @categories.each do |category| %>
              <div class="groupList">
                <label><%= category['category'] %></label>
                <div style="display:none" class="measureItemList expandableList">
                  <ul>
                   <% category['measures'].each do |measure| -%>
                     <li class="<%= measure_selected(measure['id'], current_user.selected_measures) %>" data-measure-id="<%= measure['id'] %>" data-sub-measures="<%=measure['subs'].join(',') if measure['subs']%>" data-category="<%= category['category'] %>"><%= measure['name'] %></li>
                   <% end -%>
                </div>
              </div>
            <% end %>
            
          </div>
        </li>
      </ul>
    </div>
    </div><!-- end #providerReports --> 
    <div id="dashboardPeriod">
      <div class="measureDetailTable">
        
        <% if (@selected_provider) %>
          <dl>
            <dt>Provider:</dt>
            <dd class="practiceName"><h1><%=@selected_provider.full_name%></h1></dd>
          </dl>
        <% else %>
          <%= content_tag(:h1, current_user.company) unless current_user.company.nil? || current_user.company.empty? %>
          <dl>
            <dt>Practice:</dt>
            <dd class="practiceName"><h1><%=APP_CONFIG['practice_name']%></h1></dd>
          </dl>
        <% end %>
        
        <dl>
          <dt># of Patients: </dt>
          <dd><%= @patient_count %></dd>
        </dl>
        <% unless (@selected_provider) %>
          <dl>
            <dt># of Providers: </dt>
            <dd><%= Provider.all.count %> </dd>
          </dl>
        <% end %>
        <dl>
          <div style="float: right; color: #BBB; margin-right: 255px; margin-top: 18px;"><input name="highlight_zero" id="highlight_zero" type="checkbox" checked="checked"> Highlight Zeros</div>
          <label for="amount" style="color: #BBB">Highlight:</label><span id="highlight_values" style="color: #BBB">&nbsp;delta &lt;= 5% Green and delta &gt;= 15% Red </span>
          <div id="slider-range" style="width: 400px;">
            <div id="red-slide" class="ui-slider-range ui-widget-header" style="left: 10%; width: 90%; background: #FFE3E3;"></div>
            <div id="green-slide" class="ui-slider-range ui-widget-header" style="left: 0%; width: 5%; background: #E3FFE3;"></div>
          </div>
        </dl>
        <div class="clear" style="padding: 4px;"></div>
        <div class="dashboardTabs">
          <span class="dashboardTab measures">Measures</span>
          <span class="dashboardTab active compare">Comparison</span>
        </div>
        <div style="height: 7px;"></div>
      </div><!-- end #measureDetailTable -->

      <table class="measureTable" style="float:left">
        <tr>
          <th></th>
          <th></th>
          <th style="text-align:center; padding: 0 5px">PH Num</th>
          <th style="text-align:center; padding-left: 0">QDC Num</th>
          <th style="text-align:center; padding: 0 5px">PH Den</th>
          <th style="text-align:center; padding-left: 0">QDC Den</th>
          <th></th>
        </tr>
        
        <tr style="<%= display_header(@core_measures, current_user.selected_measures)%>" class="headerRow"><td colspan="7">Core Measures</td></tr>
        <%= render :partial => "measure_compare", :collection => @core_measures %>
        <tr style="<%= display_header(@core_alt_measures, current_user.selected_measures)%>" class="headerRow"><td colspan="7">Core Alternate Measures</td></tr>
        <%= render :partial => "measure_compare", :collection => @core_alt_measures %>
        
        <% @alt_measures.each do |category, measures| %>
          <tr style="<%= display_header(measures, current_user.selected_measures)%>" class="headerRow"><td colspan="7"><%=category%></td></tr>
          <%= render :partial => "measure_compare", :collection => measures %>
        <% end %>
      </table>
    </div><!-- end #dashboardPeriod -->
  </div><!-- end #pageContent -->